version: '3'

volumes:
  bch-db1: {}
  bch-db2: {}
  bch-db3: {}

services:
  #########################################################################
  #Bitcoin core
  #########################################################################
  bch-wallet:
    build:
      context: ./docker/bch/
      dockerfile: Dockerfile
    image: cayenne-wallet-bch:0.17
    volumes:
    - ./docker/bch/data1:/root/.bitcoin
    ports:
    - "${RPC_PORT:-19332}:18332"
    stdin_open: true
    tty: true
    #    logging:
    #      driver: fluentd
    #      options:
    #        fluentd-address: "localhost:24224"
    #        tag: "docker.{{.ID}}"
    command: /usr/bin/bitcoind --printtoconsole #--conf=/root/.bitcoin/bitcoind.conf
    # docker-compose -f docker-compose.bch.yml exec bch-wallet bash
    # docker-compose -f docker-compose.bch.yml exec bch-wallet bitcoin-cli getnetworkinfo
    # /root/.bitcoin/testnet3/wallets

  #########################################################################
  #Database
  #########################################################################
  #for watch only wallet
  bch-wallet-db:
    image: mysql:5.7
    volumes:
      - bch-db1:/var/lib/mysql
      - "./docker/mysql/conf.d:/etc/mysql/conf.d"
      - "./docker/mysql/init.d:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wallet
      MYSQL_USER: cayenne
      MYSQL_PASSWORD: cayenne
    ports:
      - "${MYSQL_PORT1:-3307}:3306"

  #for cold-wallet1
  bch-cold-wallet1:
    image: mysql:5.7
    volumes:
    - bch-db2:/var/lib/mysql
    - "./docker/mysql2/conf.d:/etc/mysql/conf.d"
    - "./docker/mysql2/init.d:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cold_wallet1
      MYSQL_USER: cayenne
      MYSQL_PASSWORD: cayenne
    ports:
    - "${MYSQL_PORT2:-3308}:3306"

  #for cold-wallet2
  bch-cold-wallet2:
    image: mysql:5.7
    volumes:
    - bch-db3:/var/lib/mysql
    - "./docker/mysql2/conf.d:/etc/mysql/conf.d"
    - "./docker/mysql2/init.d:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cold_wallet1
      MYSQL_USER: cayenne
      MYSQL_PASSWORD: cayenne
    ports:
    - "${MYSQL_PORT3:-3309}:3306"
