version: '3.8'

volumes:
  watch-db: {}
  keygen-db: {}
  sign-db: {}

services:
  #########################################################################
  # Images based on
  #########################################################################
  #base-ubuntu:
  #  build:
  #    context: ./docker/ubuntu/
  #    dockerfile: Dockerfile
  #  image: wallet-ubuntu:18.04

  base-golang:
    build:
      context: ./docker/golang/
      dockerfile: Dockerfile
    image: wallet-golang:1.15.1

  #########################################################################
  # Bitcoin core
  #------------------------------------------------------------------------
  # Preparation
  # - bitcoin.conf need to be copied
  #   from ./docker/nodes/btc/data/bitcoin.conf to ./docker/nodes/btc/dataX
  #
  # Example of commands to container
  # - docker-compose exec btc-watch bash
  # - docker-compose exec btc-watch bitcoin-cli getnetworkinfo
  # - wallet location
  #   - /data/.bitcoin/testnet3/wallets
  #########################################################################
  btc-watch:
    image: lncm/bitcoind:v22.0
    volumes:
      #- ./docker/nodes/btc/data/bitcoin.conf:/data/.bitcoin/bitcoin.conf
      - ./docker/nodes/btc/data1:/data/.bitcoin
    ports:
      - "${BTC_WATCH_RPC_PORT:-19332}:18332"
    stdin_open: true
    tty: true
    #    logging:
    #      driver: fluentd
    #      options:
    #        fluentd-address: "localhost:24224"
    #        tag: "docker.{{.ID}}"
    command: --printtoconsole #--conf=/data/.bitcoin/bitcoind.conf

  btc-keygen:
    image: lncm/bitcoind:v22.0
    volumes:
      - ./docker/nodes/btc/data2:/data/.bitcoin
    ports:
      - "${BTC_KEYGEN_RPC_PORT:-19333}:18332"
    stdin_open: true
    tty: true
    #    logging:
    #      driver: fluentd
    #      options:
    #        fluentd-address: "localhost:24224"
    #        tag: "docker.{{.ID}}"
    command: -maxconnections=0 --printtoconsole #--conf=/data/.bitcoin/bitcoind.conf

  btc-sign:
    image: lncm/bitcoind:v22.0
    volumes:
      - ./docker/nodes/btc/data3:/data/.bitcoin
    ports:
      - "${BTC_SIGN_RPC_PORT:-19334}:18332"
    stdin_open: true
    tty: true
    #    logging:
    #      driver: fluentd
    #      options:
    #        fluentd-address: "localhost:24224"
    #        tag: "docker.{{.ID}}"
    command: -maxconnections=0 --printtoconsole #--conf=/data/.bitcoin/bitcoind.conf

  #########################################################################
  # Database
  #########################################################################
  # watch only wallet
  watch-db:
    image: mysql:5.7
    volumes:
      - watch-db:/var/lib/mysql #this volume should be outside to keep on a permanent basis
      - "./docker/mysql/sqls:/sqls"
      - "./docker/mysql/watch/conf.d:/etc/mysql/conf.d"
      - "./docker/mysql/watch/init.d:/docker-entrypoint-initdb.d"
      #- "./docker/mysql/scripts:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: watch
      MYSQL_USER: hiromaily
      MYSQL_PASSWORD: hiromaily
      ENV: watch
    ports:
    - "${WATCH_MYSQL_PORT:-3307}:3306"

  # keygen wallet
  keygen-db:
    image: mysql:5.7
    volumes:
      - keygen-db:/var/lib/mysql #this volume should be outside to keep on a permanent basis
      - "./docker/mysql/sqls:/sqls"
      - "./docker/mysql/keygen/conf.d:/etc/mysql/conf.d"
      - "./docker/mysql/keygen/init.d:/docker-entrypoint-initdb.d"
      #- "./docker/mysql/scripts:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keygen
      MYSQL_USER: hiromaily
      MYSQL_PASSWORD: hiromaily
      ENV: keygen
    ports:
      - "${KEYGEN_MYSQL_PORT:-3308}:3306"

  # sign wallet
  sign-db:
    image: mysql:5.7
    volumes:
      - sign-db:/var/lib/mysql #this volume should be outside to keep on a permanent basis
      - "./docker/mysql/sqls:/sqls"
      - "./docker/mysql/sign/conf.d:/etc/mysql/conf.d"
      - "./docker/mysql/sign/init.d:/docker-entrypoint-initdb.d"
      #- "./docker/mysql/scripts:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sign
      MYSQL_USER: hiromaily
      MYSQL_PASSWORD: hiromaily
      ENV: sign
    ports:
      - "${SIGN_MYSQL_PORT:-3309}:3306"

  #########################################################################
  # Open Tracing
  #------------------------------------------------------------------------
  # TODO: update docker image version to latest
  # https://hub.docker.com/r/jaegertracing/all-in-one/tags
  #########################################################################
  jaeger:
    image: jaegertracing/all-in-one:1.26
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411

  #########################################################################
  # Wallet App
  #########################################################################
#  watch-only-wallet:
#    build:
#      context: ./docker/wallet/
#      dockerfile: Dockerfile
#    image: wallet-app:1.0
#    links:
#      - btc-watch:btc-core
#      - watch-db:mysql-server
#    depends_on:
#      - btc-watch
#      - watch-db
#    environment:
#      CGO_ENABLED: 0
#      GOOS: linux
#      GO111MODULE: "on"
#    volumes:
#      - ./cmd:/go/src/github.com/hiromaily/go-bitcon/cmd
#      - ./data:/go/src/github.com/hiromaily/go-bitcon/data
#      - ./pkg:/go/src/github.com/hiromaily/go-bitcon/pkg
#      - ./go.mod:/go/src/github.com/hiromaily/go-bitcon/go.mod
#      - ./go.sum:/go/src/github.com/hiromaily/go-bitcon/go.sum
#      - ./Makefile:/go/src/github.com/hiromaily/go-bitcon/Makefile
#    stdin_open: true
#    tty: true
#    #    logging:
#    #      driver: fluentd
#    #      options:
#    #        fluentd-address: "localhost:24224"
#    #        tag: "docker.{{.ID}}"
#    command: bash
#    # docker-compose exec watch-only-wallet sh -c 'make bld-linux'
#    # docker-compose exec watch-only-wallet sh -c 'wallet -c xxx.toml xx xx'
