version: '3.8'

services:
  #########################################################################
  # Bitcoin core
  #########################################################################
  bch-watch:
    image: zquestz/bitcoin-cash-node:0.21.1
    # https://hub.docker.com/r/zquestz/bitcoin-cash-node/tags
    # https://github.com/zquestz/docker-bitcoin
    volumes:
      - ./docker/nodes/bch/data:/data
    ports:
      - "${BCH_WALLET_RPC_PORT:-19332}:18332"
    stdin_open: true
    tty: true
    #command: /usr/local/bin/bitcoind --printtoconsole --conf=/data/bitcoind.conf

# up bch-watch
# $ docker-compose -f docker-compose.bch.yml up bch-watch
# login
# $ docker-compose -f docker-compose.bch.yml exec bch-watch bash
#  - # bitcoin-cli -rpcuser=xyz -rpcpassword=xyz -rpcport=18332 getnetworkinfo
# run command
# $ docker-compose -f docker-compose.bch.yml exec bch-watch bitcoin-cli -rpcuser=xyz -rpcpassword=xyz -rpcport=18332 getnetworkinfo
