version: '3'

volumes:
  db1: {}
  db2: {}
  db3: {}

services:
  #for hot-wallet
  mysql1:
    image: mysql:5.7
    volumes:
      - db1:/var/lib/mysql
      - "./docker/mysql/conf.d:/etc/mysql/conf.d"
      - "./docker/mysql/init.d:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wallet
      MYSQL_USER: cayenne
      MYSQL_PASSWORD: cayenne
    ports:
      - "${MYSQL_PORT:-3307}:3306"

  #for cold-wallet1
  mysql2:
    image: mysql:5.7
    volumes:
    - db2:/var/lib/mysql
    - "./docker/mysql2/conf.d:/etc/mysql/conf.d"
    - "./docker/mysql2/init.d:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cold_wallet1
      MYSQL_USER: cayenne
      MYSQL_PASSWORD: cayenne
    ports:
    - "${MYSQL_PORT:-3308}:3306"

  #for cold-wallet2
  mysql3:
    image: mysql:5.7
    volumes:
    - db3:/var/lib/mysql
    - "./docker/mysql2/conf.d:/etc/mysql/conf.d"
    - "./docker/mysql2/init.d:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cold_wallet1
      MYSQL_USER: cayenne
      MYSQL_PASSWORD: cayenne
    ports:
    - "${MYSQL_PORT:-3309}:3306"
