version: '3.7'

volumes:
  btc-wallet-db: {}
  btc-keygen-db: {}
  btc-signature-db: {}

services:
  #########################################################################
  # Images based on
  #########################################################################
  base-ubuntu:
    build:
      context: ./docker/ubuntu/
      dockerfile: Dockerfile
    image: wallet-ubuntu:18.04

  base-golang:
    build:
      context: ./docker/golang/
      dockerfile: Dockerfile
    image: wallet-golang:1.14.1

  #########################################################################
  # Bitcoin core
  #########################################################################
  btc-wallet:
    build:
      context: ./docker/btc/
      dockerfile: Dockerfile
    image: wallet-btc:0.19
    volumes:
    #- btc1:/root/.bitcoin
    #- ./docs/bitcoin.example.conf:/root/.bitcoin/bitcoin.conf
    - ./docker/btc/data1:/root/.bitcoin
    ports:
    - "${BTC_WALLET_RPC_PORT:-19332}:18332"
    stdin_open: true
    tty: true
    #    logging:
    #      driver: fluentd
    #      options:
    #        fluentd-address: "localhost:24224"
    #        tag: "docker.{{.ID}}"
    command: /usr/bin/bitcoind --printtoconsole #--conf=/root/.bitcoin/bitcoind.conf
    # docker-compose exec btc-wallet bash
    # docker-compose exec btc-wallet bitcoin-cli getnetworkinfo
    # /root/.bitcoin/testnet3/wallets

  btc-keygen:
    image: wallet-btc:0.19
    volumes:
    #- btc2:/root/.bitcoin
    #- ./docs/bitcoin.example.conf:/root/.bitcoin/bitcoin.conf
    - ./docker/btc/data2:/root/.bitcoin
    ports:
    - "${BTC_KEYGEN_RPC_PORT:-19333}:18332"
    stdin_open: true
    tty: true
    #    logging:
    #      driver: fluentd
    #      options:
    #        fluentd-address: "localhost:24224"
    #        tag: "docker.{{.ID}}"
    command: /usr/bin/bitcoind -maxconnections=0 --printtoconsole
    # docker-compose exec btc-keygen bash
    # /root/.bitcoin/testnet3/wallets

  btc-signature:
    image: wallet-btc:0.19
    volumes:
    #- btc3:/root/.bitcoin
    #- ./docs/bitcoin.example.conf:/root/.bitcoin/bitcoin.conf
    - ./docker/btc/data3:/root/.bitcoin
    ports:
    - "${BTC_SIGNATURE_RPC_PORT:-19334}:18332"
    stdin_open: true
    tty: true
    #    logging:
    #      driver: fluentd
    #      options:
    #        fluentd-address: "localhost:24224"
    #        tag: "docker.{{.ID}}"
    command: /usr/bin/bitcoind -maxconnections=0 --printtoconsole
    # docker-compose exec btc-signature bash
    # /root/.bitcoin/testnet3/wallets

  #########################################################################
  # Database
  #########################################################################
  # watch only wallet
  btc-wallet-db:
    image: mysql:5.7
    volumes:
    - btc-wallet-db:/var/lib/mysql #this volume should be outside to keep on a permanent basis
    - "./docker/mysql/wallet/conf.d:/etc/mysql/conf.d"
    - "./docker/mysql/wallet/init.d:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wallet
      MYSQL_USER: hiromaily
      MYSQL_PASSWORD: hiromaily
    ports:
    - "${BTC_WALLET_MYSQL_PORT:-3307}:3306"

  # keygen wallet
  btc-keygen-db:
    image: mysql:5.7
    volumes:
    - btc-keygen-db:/var/lib/mysql #this volume should be outside to keep on a permanent basis
    - "./docker/mysql/keygen/conf.d:/etc/mysql/conf.d"
    - "./docker/mysql/keygen/init.d:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keygen
      MYSQL_USER: hiromaily
      MYSQL_PASSWORD: hiromaily
    ports:
    - "${BTC_WALLET_MYSQL_PORT:-3308}:3306"

  # signature wallet
  btc-signature-db:
    image: mysql:5.7
    volumes:
    - btc-signature-db:/var/lib/mysql #this volume should be outside to keep on a permanent basis
    - "./docker/mysql/signature/conf.d:/etc/mysql/conf.d"
    - "./docker/mysql/signature/init.d:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: signature
      MYSQL_USER: hiromaily
      MYSQL_PASSWORD: hiromaily
    ports:
    - "${BTC_WALLET_MYSQL_PORT:-3309}:3306"

  #########################################################################
  # Wallet App
  #########################################################################
#  watch-only-wallet:
#    build:
#      context: ./docker/wallet/
#      dockerfile: Dockerfile
#    image: wallet-app:1.0
#    links:
#      - btc-wallet:btc-core
#      - btc-wallet-db:mysql-server
#    depends_on:
#      - btc-wallet
#      - btc-wallet-db
#    environment:
#      CGO_ENABLED: 0
#      GOOS: linux
#      GO111MODULE: "on"
#    volumes:
#      - ./cmd:/go/src/github.com/hiromaily/go-bitcon/cmd
#      - ./data:/go/src/github.com/hiromaily/go-bitcon/data
#      - ./pkg:/go/src/github.com/hiromaily/go-bitcon/pkg
#      - ./go.mod:/go/src/github.com/hiromaily/go-bitcon/go.mod
#      - ./go.sum:/go/src/github.com/hiromaily/go-bitcon/go.sum
#      - ./Makefile:/go/src/github.com/hiromaily/go-bitcon/Makefile
#    stdin_open: true
#    tty: true
#    #    logging:
#    #      driver: fluentd
#    #      options:
#    #        fluentd-address: "localhost:24224"
#    #        tag: "docker.{{.ID}}"
#    command: bash
#    # docker-compose exec watch-only-wallet sh -c 'make bld-linux'
#    # docker-compose exec watch-only-wallet sh -c 'wallet -c xxx.toml xx xx'
