version: '3'

volumes:
  bch: {}
  db1: {}
  db2: {}
  db3: {}

services:
  #########################################################################
  #Bitcoin core
  #########################################################################
  bch:
    build:
      context: ./docker/bch/
      dockerfile: Dockerfile
    image: cayenne-wallet-bch:0.17
    volumes:
      - bch:/root/.bitcoin
      - ./bitcoin.example.conf:/root/.bitcoin/bitcoin.conf
    ports:
    - "${RPC_PORT:-19332}:18332"
    stdin_open: true
    tty: true
    #command: /usr/bin/bitcoind --conf=/root/.bitcoin/bitcoind.conf --printtoconsole
    command: /usr/bin/bitcoind --printtoconsole
    # docker-compose exec bch bash

  #########################################################################
  #Database
  #########################################################################
  #for watch only wallet
  bch-wallet-db:
    image: mysql:5.7
    volumes:
      - db1:/var/lib/mysql
      - "./docker/mysql/conf.d:/etc/mysql/conf.d"
      - "./docker/mysql/init.d:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wallet
      MYSQL_USER: cayenne
      MYSQL_PASSWORD: cayenne
    ports:
      - "${MYSQL_PORT1:-3307}:3306"

  #for cold-wallet1
  bch-cold-wallet1:
    image: mysql:5.7
    volumes:
    - db2:/var/lib/mysql
    - "./docker/mysql2/conf.d:/etc/mysql/conf.d"
    - "./docker/mysql2/init.d:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cold_wallet1
      MYSQL_USER: cayenne
      MYSQL_PASSWORD: cayenne
    ports:
    - "${MYSQL_PORT2:-3308}:3306"

  #for cold-wallet2
  bch-cold-wallet2:
    image: mysql:5.7
    volumes:
    - db3:/var/lib/mysql
    - "./docker/mysql2/conf.d:/etc/mysql/conf.d"
    - "./docker/mysql2/init.d:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cold_wallet1
      MYSQL_USER: cayenne
      MYSQL_PASSWORD: cayenne
    ports:
    - "${MYSQL_PORT3:-3309}:3306"
