version: '3.8'

services:
  #########################################################################
  # ethereum/client-go
  # - https://github.com/ethereum/go-ethereum/wiki/Running-in-Docker
  #------------------------------------------------------------------------
  # Example of commands to container
  # - Use console inside container
  #  1. $ docker compose -f docker-compose.eth.yml exec eth-node sh
  #  2. # geth attach or geth attach ipc://root/.ethereum/goerli/geth.ipc
  #  3. > eth.syncing
  # - Call JSON-RPC (https://eth.wiki/json-rpc/API)
  #   $ curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":1}' http://localhost:8545
  # - [WIP] Use console outside container
  #   $ geth attach ./docker/nodes/eth/data/geth.ipc => not working yet
  #   $ geth attach ipc:./docker/nodes/eth/data/geth.ipc => not working yet
  #   $ docker exec -it go-crypto-wallet-eth-node-1 geth attach ipc://root/.ethereum/goerli/geth.ipc => it works
  #########################################################################
  eth-node:
    # https://hub.docker.com/r/ethereum/client-go/
    image: ethereum/client-go:v1.10.15
    volumes:
      - ./docker/nodes/eth/data:/root/.ethereum/goerli
    ports:
      - "${ETH_SYNC_PORT:-30303}:30303"
      - "${ETH_RPC_PORT:-8545}:8545"
    stdin_open: true
    tty: true
    command: --goerli --http --http.addr 0.0.0.0 --http.api admin,debug,web3,eth,txpool,net,personal

  #########################################################################
  # trufflesuite/ganache-cli
  # - https://hub.docker.com/r/trufflesuite/ganache-cli
  #------------------------------------------------------------------------
  # Example of commands to container
  # - run
  #  $ docker compose -f docker-compose.eth.yml up ganache
  # - cli command example
  #  $ ganache-cli --mnemonic "toy echo orbit embrace opinion file client report history bomb regret life"
  #
  ganache:
    image: trufflesuite/ganache-cli:v6.12.2
    ports:
      - "${ETH_RPC_PORT:-8545}:8545"
    volumes:
      - ./docker/nodes/eth/ganache-data:/ganache_data
    # command adds into default ENTRYPOINT
    # https://hub.docker.com/r/trufflesuite/ganache-cli/dockerfile
    command: --mnemonic "toy echo orbit embrace opinion file client report history bomb regret life"
