version: '3.8'

services:
  #########################################################################
  # ethereum/client-go
  # - https://github.com/ethereum/go-ethereum/wiki/Running-in-Docker
  #------------------------------------------------------------------------
  # Example of commands to container
  # - Use console inside container
  #  1. $ docker compose -f docker-compose.eth.yml exec eth-node sh
  #  2. # geth attach or geth attach ipc://root/.ethereum/goerli/geth.ipc
  #  3. > eth.syncing
  # - Call JSON-RPC (https://eth.wiki/json-rpc/API)
  #   $ curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":1}' http://localhost:8545
  # - [WIP] Use console outside container
  #   $ geth attach ./docker/nodes/eth/data/geth.ipc => not working yet
  #   $ geth attach ipc:./docker/nodes/eth/data/geth.ipc => not working yet
  #   $ docker exec -it geth geth attach ipc://root/.ethereum/goerli/geth.ipc => it works
  #########################################################################
  eth-node:
    # https://hub.docker.com/r/ethereum/client-go/
    image: ethereum/client-go:v1.10.26
    container_name: geth
    volumes:
      #- ./docker/nodes/eth/goerli:/root/.ethereum/goerli
      - ./docker/nodes/eth/sepolia:/root/.ethereum/sepolia
      - ./docker/nodes/eth/jwtsecret:/data/jwtsecret
    ports:
      #- "30303:30303/tcp"
      #- "30303:30303/udp"
      - "${ETH_SYNC_PORT:-30303}:30303"
      - "${ETH_RPC_PORT:-8545}:8545"
    stdin_open: true
    tty: true
    #command: --goerli --http --http.addr 0.0.0.0 --http.api admin,debug,web3,eth,txpool,net,personal
    command:
      - --sepolia
      #- --goerli
      - --http
      - --http.addr=0.0.0.0
      - --http.port=${ETH_RPC_PORT:-8545}
      - --http.vhosts=*
      - --http.corsdomain=*
      - --http.api=admin,debug,web3,eth,txpool,net,personal
      - --authrpc.addr=0.0.0.0
      - --authrpc.port=8551
      - --authrpc.vhosts=*
      - --authrpc.jwtsecret=/data/jwtsecret
      - --maxpeers=30
      - --cache=4096

  #########################################################################
  # trufflesuite/ganache-cli
  # - https://hub.docker.com/r/trufflesuite/ganache-cli
  #------------------------------------------------------------------------
  # Example of commands to container
  # - run
  #  $ docker compose -f docker-compose.eth.yml up ganache
  # - cli command example
  #  $ ganache-cli --mnemonic "toy echo orbit embrace opinion file client report history bomb regret life"
  #
  ganache:
    image: trufflesuite/ganache-cli:v6.12.2
    container_name: ganache
    ports:
      - "${ETH_RPC_PORT:-8545}:8545"
    volumes:
      - ./docker/nodes/eth/ganache-data:/ganache_data
    # command adds into default ENTRYPOINT
    # https://hub.docker.com/r/trufflesuite/ganache-cli/dockerfile
    command: --mnemonic "toy echo orbit embrace opinion file client report history bomb regret life"
