version: '3.7'

services:
  #########################################################################
  # Bitcoin core
  #########################################################################
  bch-watch:
    build:
      context: ./docker/bch/
      dockerfile: Dockerfile
    image: wallet-bch:0.19
    volumes:
    - ./docker/bch/data:/root/.bitcoin
    ports:
    - "${BCH_WALLET_RPC_PORT:-19332}:18332"
    stdin_open: true
    tty: true
    #    logging:
    #      driver: fluentd
    #      options:
    #        fluentd-address: "localhost:24224"
    #        tag: "docker.{{.ID}}"
    command: /usr/bin/bitcoind --printtoconsole #--conf=/root/.bitcoin/bitcoind.conf
    # docker-compose -f docker-compose.bch.yml exec bch-watch bash
    # docker-compose -f docker-compose.bch.yml exec bch-watch bitcoin-cli getnetworkinfo
    # /root/.bitcoin/testnet3/wallets
