version: '3'

volumes:
  db: {}

services:
  mysql:
    image: mysql:5.7
    volumes:
      - db:/var/lib/mysql
      - "./docker/mysql/conf.d:/etc/mysql/conf.d"
      - "./docker/mysql/init.d:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wallet
      MYSQL_USER: cayenne
      MYSQL_PASSWORD: cayenne
    ports:
      - "${MYSQL_PORT:-3307}:3306"
