version: '3.7'

volumes:
  bch-wallet-db: {}
  bch-keygen-db: {}
  bch-signature-db: {}

services:
  #########################################################################
  # Bitcoin core
  #########################################################################
  bch-wallet:
    build:
      context: ./docker/bch/
      dockerfile: Dockerfile
    image: wallet-bch:0.19
    volumes:
    - ./docker/bch/data1:/root/.bitcoin
    ports:
    - "${BCH_WALLET_RPC_PORT:-19332}:18332"
    stdin_open: true
    tty: true
    #    logging:
    #      driver: fluentd
    #      options:
    #        fluentd-address: "localhost:24224"
    #        tag: "docker.{{.ID}}"
    command: /usr/bin/bitcoind --printtoconsole #--conf=/root/.bitcoin/bitcoind.conf
    # docker-compose -f docker-compose.bch.yml exec bch-wallet bash
    # docker-compose -f docker-compose.bch.yml exec bch-wallet bitcoin-cli getnetworkinfo
    # /root/.bitcoin/testnet3/wallets

  #########################################################################
  # Database
  #########################################################################
  # watch only wallet
  bch-wallet-db:
    image: mysql:5.7
    volumes:
      - bch-wallet-db:/var/lib/mysql
      - "./docker/mysql/wallet/conf.d:/etc/mysql/conf.d"
      - "./docker/mysql/wallet/init.d:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wallet
      MYSQL_USER: hiromaily
      MYSQL_PASSWORD: hiromaily
    ports:
      - "${BCH_WALLET_MYSQL_PORT:-3307}:3306"

  # keygen wallet
  bch-keygen-db:
    image: mysql:5.7
    volumes:
    - bch-keygen-db:/var/lib/mysql
    - "./docker/mysql/keygen/conf.d:/etc/mysql/conf.d"
    - "./docker/mysql/keygen//init.d:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keygen
      MYSQL_USER: hiromaily
      MYSQL_PASSWORD: hiromaily
    ports:
    - "${BCH_WALLET_MYSQL_PORT:-3308}:3306"

  # signature wallet
  bch-signature-db:
    image: mysql:5.7
    volumes:
    - bch-signature-db:/var/lib/mysql
    - "./docker/mysql/signature/conf.d:/etc/mysql/conf.d"
    - "./docker/mysql/signature/init.d:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: signature
      MYSQL_USER: hiromaily
      MYSQL_PASSWORD: hiromaily
    ports:
    - "${BCH_WALLET_MYSQL_PORT:-3309}:3306"
