version: '3.8'

services:
  #########################################################################
  # ethereum/client-go
  # - https://github.com/ethereum/go-ethereum/wiki/Running-in-Docker
  #------------------------------------------------------------------------
  # Example of commands to container
  # $ docker-compose -f docker-compose.eth.yml exec eth-node sh
  # $ geth attach ipc://root/.ethereum/goerli/geth.ipc
  # or
  # $ geth attach ./docker/nodes/eth/data/geth.ipc
  #########################################################################
  eth-node:
    # https://hub.docker.com/r/ethereum/client-go/
    image: ethereum/client-go:v1.10.15
    volumes:
      - ./docker/nodes/eth/data:/root/.ethereum/goerli
    ports:
      - "${ETH_SYNC_PORT:-30303}:30303"
      - "${ETH_RPC_PORT:-8545}:8545"
    stdin_open: true
    tty: true
    command: --goerli --http --http.addr 0.0.0.0 --http.api admin,debug,web3,eth,txpool,net,personal

  ganache:
    # https://hub.docker.com/r/trufflesuite/ganache-cli
    image: trufflesuite/ganache-cli:v6.12.2
    ports:
      - "${ETH_RPC_PORT:-8545}:8545"
    volumes:
      - ./docker/nodes/eth/ganache-data:/ganache_data
    # command adds into default ENTRYPOINT
    # https://hub.docker.com/r/trufflesuite/ganache-cli/dockerfile
    command: --mnemonic "toy echo orbit embrace opinion file client report history bomb regret life"
    # $ docker compose -f docker-compose.eth.yml up ganache
    # ganache-cli --mnemonic "toy echo orbit embrace opinion file client report history bomb regret life"
