version: '3.8'

services:
  #########################################################################
  # xrptipbot/rippled
  # - https://github.com/ripple/rippled
  # - https://xrpl.org/install-rippled.html
  # - https://xrpl.org/configure-rippled.html
  # - https://xrpl.org/connect-your-rippled-to-the-xrp-test-net.html
  #########################################################################
  xrp-node:
    # https://hub.docker.com/r/xrptipbot/rippled
    image: xrptipbot/rippled:1.5.0
    volumes:
      - ./docker/nodes/xrp/config:/config
      - ./docker/nodes/xrp/db:/var/lib/rippled/db
      - ./data/certs:/etc/ssl/certs
    ports:
      #- "${WRP_WEBSOCKET_PORT:-51233}:80"
      - "${WRP_PUBLIC_WEBSOCKET_PORT:-6005}:6005"
      - "${WRP_ADMIN_WEBSOCKET_PORT:-6006}:6006"
    stdin_open: true
    tty: true
    #command:
    #  - /opt/ripple/bin/rippled --net --conf /etc/opt/ripple/rippled.cfg
    # $ docker-compose -f docker-compose.xrp.yml exec xrp-node sh
