version: '3.8'

services:
  #########################################################################
  # ethereum/client-go
  # - https://github.com/ethereum/go-ethereum/wiki/Running-in-Docker
  #########################################################################
  eth-node:
    # https://hub.docker.com/r/ethereum/client-go/
    image: ethereum/client-go:v1.10.8
    volumes:
      - ./docker/nodes/eth/data:/root/.ethereum/goerli
    ports:
      - "${ETH_SYNC_PORT:-30303}:30303"
      - "${ETH_RPC_PORT:-8545}:8545"
    stdin_open: true
    tty: true
    command: --goerli --rpc --rpcaddr 0.0.0.0 --rpcapi admin,debug,web3,eth,txpool,net,personal
    # Then
    # $ docker-compose -f docker-compose.eth.yml exec eth-node sh
    #  # geth attach ipc://root/.ethereum/goerli/geth.ipc
    # or $ geth attach ./docker/nodes/eth/data/geth.ipc
    #      => Unable to attach to remote geth: dial unix ./docker/nodes/eth/data/geth.ipc: connect: connection refused

  #########################################################################
  # openethereum (parity was replaced by)
  # - https://github.com/openethereum/openethereum
  # - https://openethereum.github.io/
  #########################################################################
  openethereum:
    # https://hub.docker.com/r/openethereum/openethereum
    # https://openethereum.github.io/Docker
    # https://github.com/xdaichain/validator-node-dockerized/blob/master/docker-compose.yml
    image: openethereum/openethereum:v3.2.6
    init: true
    user: root
    command:
      --chain=goerli
      #--nat="extip:$EXT_IP"
      --base-path=/root/data
      --max-peers=100
      #--unlock="$ACCOUNT"
      #--password="$PASSWORD_PATH"
      --tx-time-limit=1000
      --min-gas-price=1000000000
      --gas-floor-target=17000000
      --reseal-min-period=1000
      #--engine-signer="$ACCOUNT"
      --force-sealing
      --fast-unlock
      #--metrics
      #--metrics-port=6060
      --jsonrpc-port=8545
      --jsonrpc-cors=all
      --jsonrpc-interface=all
      --jsonrpc-hosts=all
      --jsonrpc-apis=web3,eth,net,parity
      --logging="engine=trace,miner=trace"
    volumes:
      - ./data:/root/data
      #- ./password:/root/password
      #- ./key:/root/data/keys/goerli/key
    ports:
      - "${ETH_SYNC_PORT:-30303}:30303"
      - "30303:30303/udp"
      - "${ETH_RPC_PORT:-8545}:8545"
      #- "8546:8546"
    stdin_open: true
    tty: true

    # docker-compose -f docker-compose.eth.yml exec openethereum
