version: '3.7'

services:
  #########################################################################
  # ethereum/client-go
  # - https://github.com/ethereum/go-ethereum/wiki/Running-in-Docker
  #########################################################################
  eth-node:
    # https://hub.docker.com/r/ethereum/client-go/
    image: ethereum/client-go:v1.9.14
    volumes:
      - ./docker/nodes/eth/data:/root/.ethereum/goerli
    ports:
      - "${ETH_SYNC_PORT:-30303}:30303"
      - "${ETH_RPC_PORT:-8545}:8545"
    stdin_open: true
    tty: true
    command: --goerli --rpc --rpcaddr 0.0.0.0 --rpcapi admin,debug,web3,eth,txpool,net,personal
    # docker-compose -f docker-compose.eth.yml exec eth-node sh

  #########################################################################
  # parity
  # - https://openethereum.github.io/wiki/Docker
  # - FIXME: How to fix error `IPC error: File name too long (os error 36)`
  #    volume section causes this error, why mounted path of local need to be short??
  #########################################################################
  eth-parity:
    # https://hub.docker.com/r/parity/parity
    image: parity/parity:v2.7.2-stable
    volumes:
      #- ./docker/nodes/eth/parity-data/:/home/parity/.local/share/io.parity.ethereum/
      - ./parity-data/:/home/parity/.local/share/io.parity.ethereum/
    ports:
      - "${ETH_SYNC_PORT:-30303}:30303"
      - "30303:30303/udp"
      - "${ETH_RPC_PORT:-8545}:8545"
      - "8546:8546"
    stdin_open: true
    tty: true
    #command: parity --chain=goerli --geth
    command: --config .local/share/io.parity.ethereum/config.toml

    # docker-compose -f docker-compose.eth.yml exec eth-parity
