no-hooks = true
no-tests = true
output = "./pkg/models/rdb/wallet"

[mysql]
dbname = "keygen"
host = "localhost"
port = 3308
user = "root"
pass = "root"
sslmode = "false"
whitelist = [
    "seed",
    "account_key",
    "multisig_pubkey_history",
]

#[aliases.tables.tx_deposit.columns]
#current_tx_type = "CurrentTxType"
