no-hooks = true
no-tests = true
output = "./pkg/models/rdb"

[mysql]
dbname = "wallet"
host = "localhost"
port = 3307
user = "root"
pass = "root"
sslmode = "false"
whitelist = [
    "tx",
    "tx_input",
    "tx_output",
    "payment_request",
    "address",
    "seed",
    "account_key",
    "multisig_history"
]
#tinyint_as_int = true

#[aliases.tables.tx_receipt.columns]
#current_tx_type = "CurrentTxType"
