no-hooks = true
no-tests = true
output = "./pkg/models/rdb"

[mysql]
dbname = "watch"
host = "localhost"
port = 3307
user = "root"
pass = "root"
sslmode = "false"
whitelist = [
    "tx",
    "tx_input",
    "tx_output",
    "payment_request",
    "address",
    "seed",
    "account_key",
    "auth_fullpubkey",
    "auth_account_key"
]
#tinyint_as_int = true

#[aliases.tables.tx_deposit.columns]
#current_tx_type = "CurrentTxType"
