no-hooks = true
no-tests = true
output = "./pkg/models/wallet"

[mysql]
dbname = "wallet"
host = "localhost"
port = 3307
user = "root"
pass = "root"
sslmode = "false"
whitelist = [
    "tx_receipt",
    "tx_receipt_input",
    "tx_receipt_output",
    "tx_payment",
    "tx_payment_input",
    "tx_payment_output",
    "tx_transfer",
    "tx_transfer_input",
    "tx_transfer_output",
    "payment_request",
    "account_pubkey_client",
    "account_pubkey_receipt",
    "account_pubkey_payment",
    "account_pubkey_quoine",
    "account_pubkey_fee",
    "account_pubkey_stored"
]

#[aliases.tables.tx_receipt.columns]
#current_tx_type = "CurrentTxType"
