name: Test
#on: pull_request
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - name: golangci-lint for root directory
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.51.1
          working-directory: ./
          #skip-pkg-cache: true # added temporarily due to https://github.com/golangci/golangci-lint-action/issues/244
  unit-test:
    name: unit-test
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - name: Cache go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Run Unit Test
        # /home/runner/work/go-crypto-wallet/go-crypto-wallet
        working-directory: ./
        run: |
          make gotest
